# -*- coding: utf-8 -*-
"""connect_memory _with.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1brs79BGW_qykXncDtjoNdngWvU-gv8aE

# Importing dependencies
"""

# ================================
# INSTALLS
# ================================
!pip install -q \
langchain==1.2.0 \
langchain-core \
langchain-community \
langchain-huggingface \
faiss-cpu \
sentence-transformers \
transformers \
torch

# ================================
# IMPORTS
# ================================
import os
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.llms import HuggingFacePipeline
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline

# ================================
# LOAD LOCAL LLM
# ================================
model_id = "google/flan-t5-base"  # small and works on Colab
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSeq2SeqLM.from_pretrained(model_id)

text_gen_pipeline = pipeline(
    "text2text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=256
)

llm = HuggingFacePipeline(pipeline=text_gen_pipeline)

# ================================
# PROMPT: STRICT, FORMAL, 3-7 LINES
# ================================
prompt = PromptTemplate(
    template="""
You are a formal academic assistant.

Answer the question strictly using the provided context only.
Do NOT use prior knowledge or assumptions.
If the context does not fully contain the answer, reply exactly with:

"The answer is not available in the provided documents."

Answering Rules:
- Provide a complete and self-contained answer
- Define each mentioned concept separately (do not merge definitions)
- Answer must be between 3 and 7 complete sentences
- Use clear, formal, and academic language
- Summarize concepts; do NOT copy raw text, metadata, or PDF formatting
- Do NOT give partial or incomplete explanations

Context:
{context}

Question:
{question}

Answer:
""",
    input_variables=["context", "question"]
)

# ================================
# LOAD FAISS VECTORSTORE
# ================================
DB_FAISS_PATH = "/content/drive/MyDrive/PROJECTS/AI Medical Chatbot with RAG/db_faiss"

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

db = FAISS.load_local(
    DB_FAISS_PATH,
    embedding_model,
    allow_dangerous_deserialization=True
)

retriever = db.as_retriever(search_kwargs={"k": 3})

# ================================
# QA PIPELINE
# ================================
qa_chain = (
    {
        "context": retriever,
        "question": RunnablePassthrough()
    }
    | prompt
    | llm
)

# ================================
# # QUERY
# # ================================
# query = input("Write Query Here: ")
# response = qa_chain.invoke(query)

# # ================================
# # PRINT CLEAN ANSWER ONLY
# # ================================
# print("\nRESULT:\n", response)

import gradio as gr

def answer_question(question):
    if not question or question.strip() == "":
        return "Please enter a valid question."

    try:
        response = qa_chain.invoke(question)

        # If response is a dict (some LangChain versions)
        if isinstance(response, dict):
            return response.get("text", str(response))

        return str(response)

    except Exception as e:
        return f"Error: {str(e)}"


with gr.Blocks(title="Medical RAG Chatbot") as demo:
    gr.Markdown(
        """
        ## 🏥 AI Medical Chatbot (RAG)
        **Powered by FLAN-T5 + FAISS + LangChain**

        Ask questions strictly based on uploaded medical documents.
        """
    )

    with gr.Row():
        question_input = gr.Textbox(
            label="Enter your question",
            placeholder="What is pandas?",
            lines=2
        )

    answer_output = gr.Textbox(
        label="Answer",
        lines=6
    )

    submit_btn = gr.Button("Get Answer")

    submit_btn.click(
        fn=answer_question,
        inputs=question_input,
        outputs=answer_output
    )

# IMPORTANT for Hugging Face Spaces
demo.launch(server_name="0.0.0.0", server_port=7860, share=True)

